project:
  type: website
  output-dir: docs

website:
  title: "Mosquito Alert Model Monitor"
  navbar:
    left:
      - href: index.qmd
        text: Dashboard
      - href: jobs.qmd
        text: Job Details
      - href: history.qmd
        text: History
      - href: logs.qmd
        text: Logs
      - href: alerts.qmd
        text: Alerts
    right:
      - icon: github
        href: https://github.com/Mosquito-Alert/mosquito-alert-model-monitor
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
    code-fold: true
    
execute:
  freeze: false
  cache: false

# Include documentation markdown files in render
render:
  - "*.qmd"
  - "README.md"
  - "ROBUSTNESS_GUIDE.md"
  - "SLURM_SETUP.md"
  - "NOTIFICATION_SETUP.md"
  - "MACHINE_INTEGRATION_SPEC.md"
  - "RACE_CONDITION_PREVENTION.md"
  - "ARCHITECTURE.md"
