project:
  type: default
  output-dir: docs

format:
  dashboard:
    theme: cosmo
    nav-buttons: [github]
    github: https://github.com/Mosquito-Alert/mosquito-alert-model-monitor
    scrolling: true
    
execute:
  freeze: false
  cache: false
