name: mosquito-alert-monitor
channels:
  - conda-forge
  - r
dependencies:
  - r-base>=4.1
  - r-essentials
  - r-dt
  - r-plotly
  - r-jsonlite
  - r-lubridate
  - r-dplyr
  - r-purrr
  - r-stringr
  - r-ggplot2
  - r-yaml
  - r-htmltools
  - r-knitr
  - r-rmarkdown
  - quarto>=1.3
